version: '3'

services:
  influxdb:
    image: influxdb:1.7
    hostname: "influxdb"
    ports:
    - "8086:8086"
    env_file:
    - .env
    volumes:
    - "$PWD/influxdb:/var/lib/influxdb"
    networks:
    - hovel-latency
    restart: always

  grafana:
    image: "grafana/grafana:latest"
    hostname: "grafana"
    networks:
    - hovel-latency
    env_file:
    - .env
    ports:
    - "3000:3000"
    volumes:
    - "./config/grafana/provisioning:/etc/grafana/provisioning"
    restart: always

  telegraf:
    image: "telegraf:1.16"
#    image: "telegraf:latest"
    hostname: "telegraf"
    networks:
    - hovel-latency
    env_file:
    - .env
    volumes:
    - "./config/telegraf:/etc/telegraf"
    - "./config/entrypoint_telegraf.sh:/entrypoint.sh" 
    restart: always

  speedtest:
    container_name: speedtest
    build: .
    env_file:
    - .env
    networks:
    - hovel-latency
    depends_on:
    - influxdb
    restart: unless-stopped
#    command: sh -c "/wait && python3 -u speedtestlat.py"
#    environment:
#      - WAIT_HOSTS=influxdb:8086
#      - WAIT_HOSTS_TIMEOUT=300
#      - WAIT_SLEEP_INTERVAL=30
#      - WAIT_HOST_CONNECT_TIMEOUT=30



volumes:
  influxdb:


networks:
  hovel-latency:
    driver: bridge
